// Reader Rants — structured data, extracted verbatim from the original hardcoded markup.
// cuisine / neighborhood / area populated manually; neighborhood is the broad region used
// for filtering, area is the specific sub-location for display.
const staticReviews = [
  {
    "slug": "mos-tacos",
    "restaurant": "Mo's Tacos",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "This place does not miss. Not once. Not ever. I have eaten here more times than I can count and I have never walked away disappointed. The Taco Traditional is exactly what it should be. The MO's Taco is the move if you want to understand what this place is about. The Big Burrito, Wet Burrito, and Enchiladas are all worth your attention. No wait. Fair prices. Repeat customer for life.",
    "author": "The Rant Desk",
    "date": "Apr 2026",
    "cuisine": "Mexican",
    "neighborhood": "Central",
    "area": "Goshen"
  },
  {
    "slug": "mercado",
    "restaurant": "Mercado",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "The best Mexican restaurant in Fort Wayne. Full stop. We thought we had found the ceiling with Tequila out southwest, and then Mercado raised the bar so high that everything else has to answer for itself. The flavor here is not playing around — sharper, more intentional, more complex than the competition. You will pay more. You will also eat food that tastes like someone in the kitchen actually cared.",
    "author": "The Rant Desk",
    "date": "May 2022",
    "cuisine": "Mexican",
    "neighborhood": "Downtown",
    "area": "The Landing"
  },
  {
    "slug": "salvatoris-fort-wayne-north",
    "restaurant": "Salvatori's",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Salvatori's could put Casa Grande out of business and I say that knowing what Casa Grande means to people here. Everything we had was delicious and cooked to perfection. The bread is made fresh and it comes with the meal and it will ruin you for lesser bread. Bar area seating is the right call. This is a place that has figured out what it is and executes it consistently.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "Italian",
    "neighborhood": "North",
    "area": "Washington"
  },
  {
    "slug": "la-margarita",
    "restaurant": "La Margarita",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "One of my favorite places to eat in Fort Wayne and it has been that way for a long time. Never bad food. Never bad service. Those two sentences together describe a standard that most restaurants in this city cannot meet on their best days. La Margarita meets it every time. The south side does not always get its due when people talk about where to eat in this city. This is the reason that oversight is a mistake.",
    "author": "The Rant Desk",
    "date": "Mar 2026",
    "cuisine": "Mexican",
    "neighborhood": "Downtown",
    "area": "Calhoun"
  },
  {
    "slug": "black-canyon-restaurant",
    "restaurant": "Black Canyon Restaurant",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "The 10oz filet was cooked perfectly. I could not have done better at home and I take my steaks seriously. Black Canyon actually knows what medium rare means and executes it without hedging. The steak arrived at the right temperature, with the right crust, and the right internal color. In a city where ordering a steak is sometimes a gamble, Black Canyon removes the uncertainty.",
    "author": "The Rant Desk",
    "date": "Jan 2024",
    "cuisine": "American",
    "neighborhood": "Northwest",
    "area": "Dupont"
  },
  {
    "slug": "j-k-odonnells",
    "restaurant": "J K O'Donnell's",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "One of my favorite places in Fort Wayne, downtown edition. The Man Superman drink is the best thing happening right now in this city and if you have not had it yet you are operating on incomplete information. The food is always great. The staff is stellar. Shout out to McLovin — you know who you are. If you are making a downtown Fort Wayne itinerary and JK O'Donnell's is not on it, fix that.",
    "author": "The Rant Desk",
    "date": "Oct 2023",
    "cuisine": "Irish Pub",
    "neighborhood": "Downtown",
    "area": "Downtown"
  },
  {
    "slug": "claras-pizza-king",
    "restaurant": "Clara's Pizza King",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "My favorite pizza in Fort Wayne and it has been for as long as I can remember. Clara's knows what it is, has always known what it is, and has never felt the need to reinvent itself. The crust is right. The sauce is right. The ratios are right. If you grew up in Fort Wayne and did not grow up eating Clara's, I feel bad for you and think you should go correct that immediately.",
    "author": "The Rant Desk",
    "date": "May 2024",
    "cuisine": "Pizza",
    "neighborhood": "Downtown",
    "area": "North Wells"
  },
  {
    "slug": "taco-bell-reckeweg-rd",
    "restaurant": "Taco Bell",
    "score": "1–2",
    "tier": "A Crime",
    "body": "The drive-thru service was so bad I told them to keep my order and pulled off without it. I left Taco Bell without food and felt better about it. That is how bad it was. Staffed with disrespectful employees and limited supervision. There are other Taco Bell locations in this city that function like normal restaurants. This is not one of them. Avoid by address.",
    "author": "The Rant Desk",
    "date": "Oct 2021",
    "cuisine": "Fast Food",
    "neighborhood": "Southwest",
    "area": "Reckeweg"
  },
  {
    "slug": "trolley-steaks-and-seafood",
    "restaurant": "Trolley Steaks and Seafood",
    "score": "1–2",
    "tier": "A Crime",
    "body": "First time eating here and it will be the last. The food took forever. The serving dishes were dirty. My Old Fashioned glass was dirty before I even started drinking. Four people at the table all ordered different things and all walked away unsatisfied. That is not bad luck — that is a kitchen with a consistency problem and a front of house that is not paying attention. Fort Wayne has better options at every price point.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "Steakhouse",
    "neighborhood": "North",
    "area": "Dupont"
  },
  {
    "slug": "mcdonalds-goshen-rd",
    "restaurant": "McDonald's",
    "score": "1–2",
    "tier": "A Crime",
    "body": "All the buns were hard and stale. Everything tasted like it had been microwaved back to life from a previous shift. The Goshen Road location is a lost cause. There is no reason to stop here when the Coliseum location exists — management there is involved and the operation runs like it should. Do yourself a favor and drive the extra mile.",
    "author": "The Rant Desk",
    "date": "Oct 2023",
    "cuisine": "Fast Food",
    "neighborhood": "North",
    "area": "Goshen"
  },
  {
    "slug": "hideout-125",
    "restaurant": "Hideout 125",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "We went specifically for the Old Fashioned and it delivered. The atmosphere and vibe at Hideout 125 are second to none in Fort Wayne. Shout out to Noah, the manager, who took care of our table like we were regulars even on our first visit. That kind of hospitality is not something you can train into people who do not already have it. The cocktail program here is serious. Go for the Old Fashioned. Come back regularly.",
    "author": "The Rant Desk",
    "date": "Feb 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "North",
    "area": "Dupont"
  },
  {
    "slug": "halls-original-drive-in",
    "restaurant": "Hall's Original Drive In",
    "score": "5–6",
    "tier": "Meh",
    "body": "The food is a dice roll and the dice do not always land in your favor. I tested the pan fried Cod dinner two days in a row — day one was fantastic, day two was nowhere near as good. Same dish, same location, wildly different result. On a good night Hall's is a solid south side classic with a wait staff that genuinely takes care of you. On a bad night the kitchen is carrying the place on atmosphere alone. Keep coming back, keep hoping.",
    "author": "The Rant Desk",
    "date": "Oct 2021",
    "cuisine": "American",
    "neighborhood": "North",
    "area": "Lima"
  },
  {
    "slug": "casa-grande",
    "restaurant": "Casa Grande",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "One of my favorite Mexican restaurants in Fort Wayne through years of consistent performance. I have never been disappointed here and everyone I have brought for the first time has left as a return customer. There are two locations — both are good but the Dupont location has the edge on plating and presentation. The kind of neighborhood restaurant that Fort Wayne should be proud of.",
    "author": "The Rant Desk",
    "date": "Nov 2021",
    "cuisine": "Mexican",
    "neighborhood": "Northeast",
    "area": "Northeast"
  },
  {
    "slug": "big-apple-pizza",
    "restaurant": "Big Apple Pizza",
    "score": "3–4",
    "tier": "Bad",
    "body": "Updated review because this place used to be a must-visit and it is not that anymore. I have been here over a dozen times. The early visits were great — the pizza was fantastic, the garlic knots were worth the trip. Something changed. The quality dropped and kept dropping. Big Apple was a legitimate Fort Wayne pizza destination for years. Whatever happened in the kitchen, the result is a place coasting on a reputation it is no longer earning.",
    "author": "The Rant Desk",
    "date": "Sep 2023",
    "cuisine": "Pizza",
    "neighborhood": "Downtown",
    "area": "Downtown"
  },
  {
    "slug": "old-gas-house-restaurant",
    "restaurant": "Old Gas House Restaurant",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "We eat here once a week and we always leave fat and happy. The Old Gas House is one of those Fort Wayne institutions that locals know about and outsiders discover with a look of surprise on their face — surprised that a building this old is serving food this consistently good. The location on the river is a bonus. The food would be worth it without the view. Never a bad meal here. Never a bad experience.",
    "author": "The Rant Desk",
    "date": "Oct 2021",
    "cuisine": "Steakhouse",
    "neighborhood": "Downtown",
    "area": "Downtown"
  },
  {
    "slug": "breakfast-clubb",
    "restaurant": "Breakfast Clubb",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Top three breakfast spots in Fort Wayne and I will not hear arguments. Breakfast Clubb has earned its reputation and continues to earn it every time I walk through the door. The portions are honest. The food is cooked right. The coffee situation is handled. This is the place you take visitors when you want to show them what Fort Wayne can do. Go early or accept the wait — the crowd knows what it is doing.",
    "author": "The Rant Desk",
    "date": "Jan 2022",
    "cuisine": "Breakfast",
    "neighborhood": "North",
    "area": "St Joe"
  },
  {
    "slug": "blaze-pizza",
    "restaurant": "Blaze Pizza",
    "score": "5–6",
    "tier": "Meh",
    "body": "It is like going to Subway except for pizza and I do not mean that as a compliment. Our order was lost, then undercooked, then lost again in one lunch visit. The pizza itself is fine when it arrives intact but Blaze has an operational consistency problem at this location they have not fixed. On a slow day this is solid fast-casual pizza. On a busy day you are rolling the dice on whether your order makes it to you.",
    "author": "The Rant Desk",
    "date": "Apr 2023",
    "cuisine": "Pizza",
    "neighborhood": "North",
    "area": "Coliseum"
  },
  {
    "slug": "birrieria-la-cabana",
    "restaurant": "Birrieria La Cabaña",
    "score": "3–4",
    "tier": "Bad",
    "body": "The food was bland. The main ingredient in the guacamole was onion — not avocado, onion. The birria had no seasoning. Not even salt. The birria. Fort Wayne's Mexican food scene has real options and this is not one of them. When the signature dish of a Mexican restaurant tastes like it forgot to season itself, there is nothing left to recommend. Skip it.",
    "author": "The Rant Desk",
    "date": "Jan 2024",
    "cuisine": "Mexican",
    "neighborhood": "East",
    "area": "New Haven"
  },
  {
    "slug": "henrys-restaurant",
    "restaurant": "Henry's Restaurant",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always a great experience at Henry's. The food is fantastic and the service is great. The menu is not over-expanded — everything on it is actually good, which is more discipline than most Fort Wayne restaurants show. If you are in the Fort you have to try it. This is a downtown gem that does not oversell itself and does not need to. The food does the talking.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "American",
    "neighborhood": "Downtown",
    "area": "Downtown"
  },
  {
    "slug": "club-soda",
    "restaurant": "Club Soda",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always a good spot when you are downtown. The staff, food, and drinks here are in the top 10% of the city — that is not a low bar, that is a real statement about what Club Soda has built over the years. The desserts are worth a mention and rarely get one. If you are doing downtown Fort Wayne and you skip Club Soda, you made a mistake. Correct it next time.",
    "author": "The Rant Desk",
    "date": "Dec 2021",
    "cuisine": "American",
    "neighborhood": "Downtown",
    "area": "Downtown"
  },
  {
    "slug": "ihop-w-jefferson-blvd",
    "restaurant": "IHOP",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "There is a stellar crew working at the Jefferson location. Hospitality is phenomenal and that is not something you expect to say about an IHOP. The food is what it is — it is IHOP — but when the staff runs the room this well, the whole experience gets elevated. Not every location operates like this. This one does. Worth the stop.",
    "author": "The Rant Desk",
    "date": "Feb 2026",
    "cuisine": "Breakfast",
    "neighborhood": "Southwest",
    "area": "Jefferson"
  },
  {
    "slug": "black-dog-pub",
    "restaurant": "Black Dog Pub",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Good variety of drinks with beer leading the charge, but there are some surprise deals on the food side that most people overlook. The waitress we had was quick and had the whole table taken care of all night without being asked twice for anything. The atmosphere is a five — this place has figured out what a neighborhood pub should feel like. Definitely recommend.",
    "author": "The Rant Desk",
    "date": "Feb 2026",
    "cuisine": "Pub",
    "neighborhood": "Southwest",
    "area": "Covington"
  },
  {
    "slug": "crust-brewing-rosemont-il",
    "restaurant": "Crust Brewing",
    "score": "3–4",
    "tier": "Bad",
    "body": "Walking in I was hit with a wall of noise and chaos with no real theme — just a jumble of everything happening at once. Ordered the Philly Za pizza. Big mistake. A Philly cheesesteak pizza should have steak, peppers, and cheese in some recognizable proportion. What arrived was a soggy mess with ingredients that did not belong together and none of them cooked to the right temperature. The concept is interesting on paper. The execution is not there.",
    "author": "The Rant Desk",
    "date": "Mar 2025",
    "cuisine": "Pizza",
    "neighborhood": "Rosemont, IL",
    "area": "Rosemont"
  },
  {
    "slug": "raising-canes-chicken-fingers",
    "restaurant": "Raising Cane's Chicken Fingers",
    "score": "3–4",
    "tier": "Bad",
    "body": "Not sure what all the hype is for this place. It is chicken. That is it. I had it for the first time and it is not on my priority list to revisit. Is it good? Yes. Is it excellent? No. The menu is so limited that if you do not love their specific style of chicken you have nowhere to go. Fort Wayne has better chicken options that do not come with this much marketing attached to them.",
    "author": "The Rant Desk",
    "date": "Jan 2025",
    "cuisine": "Fast Food",
    "neighborhood": "North",
    "area": "Coliseum"
  },
  {
    "slug": "culvers",
    "restaurant": "Culver's",
    "score": "3–4",
    "tier": "Bad",
    "body": "One Concrete Mixer. That is all I wanted. I pulled through the drive-thru at 9:30, they close at 10, and the line was backed up mostly because people in this country cannot grasp that when the car ahead of you moves, you move too. I cut through, parked in the number one waiting spot, and sat there over twenty-five minutes for a single Concrete. Eventually I walked inside to claim my own order. The first employee I asked took my number, said nothing, and walked away. The people next to me were standing there for the exact same reason. This was not understaffing either — there were ten to twelve people behind that counter. I would have been better off buying the ingredients and making it myself. One young man apologized for the wait and I told him it was not his fault, because it wasn't. This is where we are now.",
    "author": "The Rant Desk",
    "date": "Feb 2022",
    "cuisine": "Fast Food",
    "neighborhood": "Northwest",
    "area": "Washington Center"
  },
  {
    "slug": "the-lucky-turtle-grill",
    "restaurant": "The Lucky Turtle Grill",
    "score": "5–6",
    "tier": "Meh",
    "body": "I want to love this place, and honestly I keep going back for the feel of it — the little booths, the quiet, the cozy without trying to be romantic. The staff is always fun and genuinely helpful, and there is a full bar with a few specialty beers. The food is the letdown. Everything I have had is just okay, nothing worth recommending. The cheese sticks came out warm but not melted, no gooey pull, just warm. The blackened mahi tacos were long, thin, skimpy filets with no real flavor — I would have taken frozen Gordon's fish sticks over them. The flatbread had plenty of toppings but no pop in the sauce, a crispy golden crust I cut off and ate, and a limp, chewy bottom. I will keep coming back. But going forward, I am an appetizers-only man here.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "American",
    "neighborhood": "North",
    "area": "Dupont"
  },
  {
    "slug": "ocharleys-restaurant-and-bar",
    "restaurant": "O'Charley's Restaurant & Bar",
    "score": "5–6",
    "tier": "Meh",
    "body": "Hit and miss, and I mean that literally — I have had great food here and I have sent food back because it was that bad. The servers, though, are fantastic and take real care of us every time. The kitchen is the wild card. On a revisit things were on point, the menu had expanded, and the new items impressed the whole table. Then my chicken tenders came out like rubber. I didn't send them back, I just didn't finish them. The floor staff earns the visit. The kitchen has to decide who it wants to be.",
    "author": "The Rant Desk",
    "date": "Jul 2023",
    "cuisine": "American",
    "neighborhood": "Southwest",
    "area": "Illinois Rd"
  },
  {
    "slug": "conners-rooftop",
    "restaurant": "Conner's Rooftop",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "We hit this place every few months, and that is about the right pace, because the size and the cost keep it from being a regular. There are some signature drinks and a limited menu, but the price is the sticking point — premium prices should come with premium drinks, and that is not quite what you get. The atmosphere is fine, the layout has no real flow, and the rooftop view to the south and west is mostly other buildings, so do not come for the skyline. All that said, it is still worth a visit. It just doesn't quite land for me and my crew.",
    "author": "The Rant Desk",
    "date": "Jan 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "Downtown",
    "area": "Jefferson"
  },
  {
    "slug": "tequila-mexican-restaurant-and-cantina",
    "restaurant": "Tequila Mexican Restaurant & Cantina",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Round two and this place delivers. The food and drinks are excellent — my only knock is the plates came out hot but the food only warm. The flavors are sharp and unmistakable, nothing muddy or timid. The drinks are the real story, and the Texas margarita was dialed in. Our server-bartender Amanda was one of the best we have had in a long, long time, and Raul earned a mention too for coming table-side to walk us through the dessert menu and handle special requests. We are already planning the next visit.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "Mexican",
    "neighborhood": "Southwest",
    "area": "Jefferson"
  },
  {
    "slug": "mi-pueblo-mexican-restaurant",
    "restaurant": "Mi Pueblo Mexican Restaurant",
    "score": "5–6",
    "tier": "Meh",
    "body": "Hit and miss on the same table. My plate came out hot but the food only warm, while the other dishes came out hot food on hot plates. The food was good but could have been better, the desserts were good but could have been better, and the margaritas had no tequila in them, which is a hard thing to forgive at a Mexican restaurant. If the food came out hot and the margaritas actually had tequila, this is knocking on the door of a Must Visit. It isn't there yet.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "Mexican",
    "neighborhood": "Downtown",
    "area": "Jefferson"
  },
  {
    "slug": "proof",
    "restaurant": "Proof°",
    "score": "5–6",
    "tier": "Meh",
    "body": "I didn't get to eat — the place was slammed and the menu is burgers, wings, and other fried things, so I will be back for that. What I can speak to is the house old fashioned, and that is where the score comes from. It was a lot of Maker's Mark in a glass with ice, simple syrup, and a cherry-orange peel. That is not an old fashioned with any craft behind it, that is bourbon with garnish. The staff was good but clearly understaffed and running hard. Would I go back? Yes — to eat, not to drink.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "Downtown",
    "area": "Calhoun"
  },
  {
    "slug": "cebollas-mexican-grill",
    "restaurant": "Cebolla's Mexican Grill",
    "score": "5–6",
    "tier": "Meh",
    "body": "A reliable spot to meet family and friends, and they will seat a group of six or more without a reservation, which counts for something. The food is always good but it sits right at the level of every other place with the same menu — nothing that separates it from the pack, except the salsa, which genuinely rocks. Service and food come out fast, drink refills never lag, alcoholic or not. Solid, dependable, middle of the road.",
    "author": "The Rant Desk",
    "date": "Oct 2021",
    "cuisine": "Mexican",
    "neighborhood": "Southwest",
    "area": "Jefferson"
  },
  {
    "slug": "casa-ristorante",
    "restaurant": "Casa Ristorante",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "This was a takeout review, so grade accordingly. The food was good — the spaghetti came a touch undercooked, slightly chewy, not quite al dente, and the meatballs were big but needed more heat, though that is partly on takeout. Where it shined was the desserts, the breadsticks, and the sauces, all fantastic. It runs a little costly for what you get. Worth a visit for sure, just not a place I would put in the weekly rotation. That's my take.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "Italian",
    "neighborhood": "Southwest",
    "area": "Jefferson"
  },
  {
    "slug": "the-bradley",
    "restaurant": "The Bradley",
    "score": "5–6",
    "tier": "Meh",
    "body": "This is for the bar only, we did not stay at the hotel, and this is strictly my opinion — the Bradley is overrated. Subpar drinks at high prices, and a view that is nothing to write home about. The service was good but slow, which I chalk up to being short staffed. Worth one visit to say you have been. Worth a second? Not for me.",
    "author": "The Rant Desk",
    "date": "Jan 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "Downtown",
    "area": "Main St"
  },
  {
    "slug": "big-eyed-fish-express",
    "restaurant": "Big Eyed Fish Express",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always good food and we eat here a lot. The Cajun broiled cod dinner is my go-to. My one gripe is portion size — it could be bigger for the price. But it is a solid, dependable place to get good fish, the burgers hold their own, and the tartar sauce is the best we have ever had. That is not a throwaway line — the best we have ever had.",
    "author": "The Rant Desk",
    "date": "Apr 2023",
    "cuisine": "Seafood",
    "neighborhood": "Central",
    "area": "Hillegas"
  },
  {
    "slug": "solbird-kitchen-and-tap",
    "restaurant": "SOLBIRD Kitchen & Tap",
    "score": "5–6",
    "tier": "Meh",
    "body": "This is a first-pass verdict, because I only got the brunch menu, which was limited — expected — but the choices themselves were not that exciting. The back-of-house tacos were the best thing that hit our table. I am holding my real judgment until I get in and order off the regular menu. More to come, but brunch alone did not make the case.",
    "author": "The Rant Desk",
    "date": "May 2023",
    "cuisine": "American",
    "neighborhood": "Northwest",
    "area": "Dupont"
  },
  {
    "slug": "office-tavern",
    "restaurant": "Office Tavern",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Great place to drop in for some food and karaoke on the right night. The staff is easy to like and the regulars are friendly, which is half of what makes a neighborhood tavern work. Solid choice of bourbons and other liquors, which is exactly what I am there for. Recommend it without hesitation, and I will be back very soon.",
    "author": "The Rant Desk",
    "date": "Nov 2021",
    "cuisine": "Pub",
    "neighborhood": "Southwest",
    "area": "Brooklyn"
  },
  {
    "slug": "whats-up-pub-and-grub",
    "restaurant": "What's Up Pub & Grub",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "If you want to watch a game — any game, any sport — there are TVs in every corner of this place. Great food, and the service was excellent. We rolled in a party of ten and missed out on nothing, entirely thanks to a server who never let us fall behind. That is a hard thing to pull off with a table that size, and they nailed it.",
    "author": "The Rant Desk",
    "date": "Jan 2022",
    "cuisine": "Pub",
    "neighborhood": "North",
    "area": "Woodland"
  },
  {
    "slug": "the-tower-bar-and-grill",
    "restaurant": "The Tower Bar & Grill",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "I come for the wings, every time. The Tower grilled boneless are my order, with a basket of fries, and they come out fast and hot. Service is quick and courteous, the food keeps pace, and the drink prices are great — just know it is a basic drink menu, nothing fancy. But that is not why you come here. You come for the wings, and the wings deliver.",
    "author": "The Rant Desk",
    "date": "Dec 2023",
    "cuisine": "Bar & Grill",
    "neighborhood": "Central",
    "area": "State Blvd"
  },
  {
    "slug": "arena-bar-and-grill",
    "restaurant": "Arena Bar & Grill",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always good food when the kitchen is open, and that is the one catch — check the hours. The night I was in, the place was packed and karaoke was going full tilt. Young crowd, but it was that time of year for it. This is a great spot to meet up for food, drinks, sports, and karaoke all under one roof. It does a little of everything and does it well enough to keep me coming back.",
    "author": "The Rant Desk",
    "date": "Nov 2021",
    "cuisine": "Bar & Grill",
    "neighborhood": "North",
    "area": "Dupont"
  },
  {
    "slug": "morgans-tap-and-grill",
    "restaurant": "Morgan's Tap & Grill",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "I did not eat this time — met friends here for drinks — so grade the food on their word, not mine. The staff is genuinely friendly and always smiling, which goes a long way, and the prices are good. My friends who ate said the food was really good. On the strength of the room, the service, and the prices, this earns the visit. I will report back on the food when I have had it myself.",
    "author": "The Rant Desk",
    "date": "Feb 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "Waynedale",
    "area": "Bluffton"
  },
  {
    "slug": "the-club-room-at-the-clyde",
    "restaurant": "The Club Room at The Clyde",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "A great place for live entertainment, food, and drinks. It is always packed, but the crew knows how to accommodate and gets you seated without the wait becoming a problem. That is a skill, keeping a full house moving. Highly recommend it — a genuinely fantastic spot and one of the better nights out on this side of town.",
    "author": "The Rant Desk",
    "date": "Dec 2021",
    "cuisine": "Bar & Grill",
    "neighborhood": "Waynedale",
    "area": "Bluffton"
  },
  {
    "slug": "summit-grill-kitchen-and-cocktails",
    "restaurant": "Summit Grill Kitchen & Cocktails",
    "score": "5–6",
    "tier": "Meh",
    "body": "This is a drinks-and-appetizers verdict, because that is all we had. The atmosphere is good — a wide, open space that breathes. The problem was the menu itself: nothing caught my eye outside of the appetizers. That is not a great sign when you are looking to eat. Fine for a drink and a snack, but nothing pulled me toward a full meal. I will hold final judgment until something on that menu gives me a reason to.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "American",
    "neighborhood": "Southwest",
    "area": "Covington"
  },
  {
    "slug": "chick-fil-a-coliseum",
    "restaurant": "Chick-fil-A (Coliseum)",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Packed as usual, and worth the wait as usual — that is the whole Chick-fil-A equation. The Southwest salad is my go-to, and I cheat with a chicken sandwich every now and then, because of course I do. The line moves faster than a line that long has any right to. Consistent, quick, and they have the drive-thru chaos figured out better than anyone else in the game.",
    "author": "The Rant Desk",
    "date": "Nov 2021",
    "cuisine": "Fast Food",
    "neighborhood": "North",
    "area": "Coliseum"
  },
  {
    "slug": "chick-fil-a-apple-glen",
    "restaurant": "Chick-fil-A (Apple Glen)",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Same standard as the Coliseum location. Chick-fil-A is consistent across the board — that is the entire point of the place — and Apple Glen holds the line. Fast, reliable, exactly what you expect walking in. No surprises, and in fast food, no surprises is a compliment.",
    "author": "The Rant Desk",
    "date": "Jul 2023",
    "cuisine": "Fast Food",
    "neighborhood": "Southwest",
    "area": "Apple Glen"
  },
  {
    "slug": "big-eyed-fish-wells-st",
    "restaurant": "Big Eyed Fish (Wells St)",
    "score": "5–6",
    "tier": "Meh",
    "body": "Good food and good service — I am always a fan of a solid fish plate, and this location delivers on the basics. My one note, and it is the same thing I would tell them to their face: the menu could use an expansion. What is there is done right, there just is not enough of it. A little more range and this moves up. As it stands, it is a dependable, no-frills fish stop.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "Seafood",
    "neighborhood": "Central",
    "area": "Wells St"
  },
  {
    "slug": "mitchells-venue",
    "restaurant": "Mitchell's Venue",
    "score": "5–6",
    "tier": "Meh",
    "body": "Always a good time here — but Jesus, is it always packed. That is the whole review in a sentence. When it is this crowded, getting a drink is a mission, getting food is a longer one, and using the restroom becomes a strategic operation. The energy is there and the good time is real, but the crowds are the cost of admission. Come knowing you will be fighting for everything.",
    "author": "The Rant Desk",
    "date": "Feb 2022",
    "cuisine": "Bar & Grill",
    "neighborhood": "Southwest",
    "area": "Jefferson"
  },
  {
    "slug": "red-robin-gourmet-burgers-and-brews",
    "restaurant": "Red Robin Gourmet Burgers and Brews",
    "score": "5–6",
    "tier": "Meh",
    "body": "The food came out cold, so they remade it — no argument, no attitude, just fixed it. And that is the saving grace here: the server was great and took care of everything for us. Cold food is a kitchen problem, but a floor that handles it right keeps the whole thing from tanking. Middle of the road on the food, better than that on the service.",
    "author": "The Rant Desk",
    "date": "Nov 2023",
    "cuisine": "American",
    "neighborhood": "North",
    "area": "Coldwater"
  },
  {
    "slug": "crumbl",
    "restaurant": "Crumbl",
    "score": "5–6",
    "tier": "Meh",
    "body": "Good cookies, but overhyped, in my opinion. That is the honest verdict. I have had better and I have had much worse, which puts Crumbl squarely in the middle despite all the noise around it. The rotating menu is a fun idea and the cookies are perfectly fine. Just do not walk in expecting the life-changing experience the internet keeps promising you. They are cookies. Good ones. Not magic.",
    "author": "The Rant Desk",
    "date": "May 2023",
    "cuisine": "Dessert",
    "neighborhood": "Southwest",
    "area": "Thomas"
  },
  {
    "slug": "07-pub",
    "restaurant": "07 Pub",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Great food and a great atmosphere — this is a real neighborhood pub that gets the fundamentals right. The pizza is a must, full stop, order it. And I have to give it up for the old fashioned, which they actually make with some care. Good food, good drink, good room. That is the trifecta, and 07 hits all three.",
    "author": "The Rant Desk",
    "date": "Dec 2021",
    "cuisine": "Pub",
    "neighborhood": "South",
    "area": "Broadway"
  },
  {
    "slug": "redwood-inn",
    "restaurant": "Redwood Inn",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always great food and always great service — the kind of consistency that makes a place a staple. And the headline: the pizza is some of the best in town. That is not a claim I throw around lightly in a town that takes its pizza seriously. Redwood earns it. A dependable, no-drama spot that just keeps delivering.",
    "author": "The Rant Desk",
    "date": "Feb 2022",
    "cuisine": "Pizza",
    "neighborhood": "Central",
    "area": "Main St"
  },
  {
    "slug": "tcby-georgetown-square",
    "restaurant": "TCBY - Georgetown Square",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "This place is a must, and the reason is simple: there is always something new to try. That rotating variety is what keeps it from getting stale, and it keeps me coming back to see what is on offer. Sometimes you want the reliable froyo fix, and TCBY delivers it every time with enough rotation to stay interesting.",
    "author": "The Rant Desk",
    "date": "Mar 2022",
    "cuisine": "Dessert",
    "neighborhood": "Northeast",
    "area": "State Blvd"
  },
  {
    "slug": "pizza-king-waynedale",
    "restaurant": "Pizza King (Waynedale)",
    "score": "7–8",
    "tier": "Must Visit",
    "body": "Always great pizza, and the last visit was no different — loved every bite of it. This is the Waynedale Pizza King, and it earns its spot. There is no reinvention happening here, no gimmick, just a pie done right every single time you walk in. When a place is this consistent, you stop questioning it and just order. Fantastic pizza, full stop.",
    "author": "The Rant Desk",
    "date": "Jan 2022",
    "cuisine": "Pizza",
    "neighborhood": "Waynedale",
    "area": "Bluffton"
  },
  {
    "slug": "arcos",
    "restaurant": "Arco's",
    "score": "5–6",
    "tier": "Meh",
    "body": "Arco's took over the old Bandidos spot in Waynedale, and the food is better than what was here before — but let us be honest about what it is. Nothing is bland exactly, there is just not a lot of flavor going on. The salsa is mid-grade at best. The whole operation reads like an upscale Taco Bell: cleaner, a step up, but not the authentic punch you want from a Mexican kitchen. It is fine. It fills the gap. It is not a place I am going out of my way for.",
    "author": "The Rant Desk",
    "date": "Apr 2022",
    "cuisine": "Mexican",
    "neighborhood": "Waynedale",
    "area": "Winchester"
  }
];
